# Generated by Django 3.2.9 on 2021-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_concentrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ironconcentrate',
            name='aluminium',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ironconcentrate',
            name='calcium',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ironconcentrate',
            name='iron',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ironconcentrate',
            name='silicon',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ironconcentrate',
            name='sulfur',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
